version: "3"

services:
  rabbit:
    image: rabbitmq:3-management
    platform: linux/amd64
    ports:
      - "7070:15672"
      - "4369:4369"
      - "5672:5672"
    networks:
      - network
    restart: always
  mysql:
    image: mysql:8.0
    platform: linux/amd64
    volumes:
      - /mysql:/var/lib/mysql
    networks:
      - network
    environment:
      MYSQL_ROOT_PASSWORD: "starbucks"
    restart: always
  cashier:
    image: starbucks-cashier
    platform: linux/amd64
    ports:
      - 9090:9090
    depends_on:
      - kong
    volumes:
      - /tmp:/tmp
    networks:
      - network
    environment:
      MYSQL_HOST: "mysql"
      MYSQL_USERNAME: "root"
      MYSQL_PASSWORD: "starbucks"
      API_KEY: "?apikey=2H3fONTa8ugl1IcVS7CjLPnPIS2Hp9dJ"
      API_HOST: "kong:8000"
    restart: always
  worker:
    image: spring-starbucks-worker
    platform: linux/amd64
    depends_on:
      - mysql
      - rabbit
    networks:
      - network
    environment:
      MYSQL_HOST: "mysql"
      MYSQL_USERNAME: "root"
      MYSQL_PASSWORD: "starbucks"
      RABBIT_HOST: "rabbit"
      RABBIT_USERNAME: "guest"
      RABBIT_PASSWORD: "guest"
    restart: always
    deploy:
      mode: replicated
      replicas: 2
  kong:
    image: kong:2.4.0
    platform: linux/amd64
    depends_on:
      - lb
    networks:
      - network
    restart: always
    ports:
      - "80:8000"
      - "443:8443"
      - "8001:8001"
      - "8444:8444"
    environment:
      KONG_DATABASE: "off"
      KONG_PROXY_ACCESS_LOG: "/dev/stdout"
      KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
      KONG_PROXY_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
  starbucks:
    image: spring-starbucks-api
    depends_on:
      - mysql
      - rabbit
    volumes:
      - /tmp:/tmp
    networks:
      - network
    ports:
      - 8080
    environment:
      MYSQL_HOST: "mysql"
      MYSQL_USERNAME: "root"
      MYSQL_PASSWORD: "starbucks"
      RABBIT_HOST: "rabbit"
      RABBIT_USERNAME: "guest"
      RABBIT_PASSWORD: "guest"
    restart: always
  lb:
    image: eeacms/haproxy
    platform: linux/amd64
    depends_on:
      - starbucks
    ports:
      - "90:5000"
      - "1936:1936"
    environment:
      BACKENDS: "starbucks"
      BACKENDS_PORT: "8080"
      DNS_ENABLED: "true"
      COOKIES_ENABLED: "false"
      LOG_LEVEL: "info"
    networks:
      - network

volumes:
  schemas:
    external: false

networks:
  network:
    driver: bridge