version: '3.8'
services:
  mysql:
    image: mysql:8.0
    platform: linux/amd64
    volumes:
      - /mysql:/var/lib/mysql
    networks:
      - network
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "starbucks"
    restart: always

  starbucks-cashier:
    image: starbucks-cashier
    platform: linux/amd64
    depends_on:
      - mysql
    volumes:
      - /tmp:/tmp
    networks:
      - network
    ports:
      - "9090:9090"
    environment:
      API_KEY: "2H3fONTa8ugl1IcVS7CjLPnPIS2Hp9dJ"
    restart: always


  starbucks-api:
    image: spring-starbucks-api
    depends_on:
      - mysql
    volumes:
      - /tmp:/tmp
    networks:
      - network
    ports:
      - 8080
    environment:
      MYSQL_HOST: "mysql"
      MYSQL_USER: "root"
      MYSQL_PASS: "starbucks"
    restart: always
  #lb:
  #  image: eeacms/haproxy
  #  platform: linux/amd64
   # depends_on:
    #  - starbucks-cashier
    #ports:
    #  - "80:5000"
    #  - "1936:1936"
    #environment:
     # BACKENDS: "starbucks-cashier"
     # BACKENDS_PORT: "9090"
     # DNS_ENABLED: "true"
    #  COOKIES_ENABLED: "false"
     # LOG_LEVEL: "info"
    #networks:
   #   - network

volumes:
  mysql-data:

networks:
  network:
    external:
      name: kong-network