apiVersion: v1
kind: Service
metadata:
  name: spring-starbucks-worker-service
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 7070
    targetPort: 7070
  selector:
    name: spring-starbucks-worker
